###
GET http://localhost:3000/api/articulos HTTP/1.1

###
POST http://localhost:3000/api/articulos/panaderia HTTP/1.1
Content-Type: application/json

{
    "nombre": "Patricio",
    "precio": 1,
    "url": "./assets/pan-tostado.png"
}

###
GET http://localhost:3000/api/articulos/pan HTTP/1.1


###
DELETE http://localhost:3000/api/articulos/pan/2



###
PATCH http://localhost:3000/api/articulos?categoria=panaderia&id=7 HTTP/1.1
Content-Type: application/json

{   
    "nombre": "Skibidy",
    "url": "./assets/leche-tetra.png"   
}       


###